name: platinum_karaoke_digital_songbook
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  draggable_scrollbar: ^0.0.4
  path_provider: ^1.6.24
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/platinumSongs.db
    - assets/songbook.png

  fonts:
    - family: Allan
      fonts:
        - asset: fonts/Allan/Allan-Regular.ttf
        - asset: fonts/Allan/Allan-Bold.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-VariableFont_wght.ttf
